sched/debug: Add missing __PS() macro
kernel/sched/debug.c:1076:2: error: implicit declaration of function
'__PS' [-Werror,-Wimplicit-function-declaration]
 1076 |         __PS("uclamp.min", p->uclamp[UCLAMP_MIN].value);
      |         ^